# ATTENTION: auto generated from C++ code, use `make stubgen` to update!
"""
rcs franka module
"""
from __future__ import annotations

import typing

import numpy
import pybind11_stubgen.typing_ext
import rcs._core.common

from . import exceptions

__all__: list[str] = [
    "FHConfig",
    "FHState",
    "FR3Config",
    "Franka",
    "FrankaConfig",
    "FrankaHand",
    "FrankaLoad",
    "FrankaState",
    "IKSolver",
    "PandaConfig",
    "RobotMode",
    "RobotState",
    "exceptions",
    "franka_ik",
    "kAutomaticErrorRecovery",
    "kGuiding",
    "kIdle",
    "kMove",
    "kOther",
    "kReflex",
    "kUserStopped",
    "rcs_ik",
]

class FHConfig(rcs._core.common.GripperConfig):
    async_control: bool
    epsilon_inner: float
    epsilon_outer: float
    force: float
    grasping_width: float
    ip: str
    speed: float
    def __init__(
        self,
        ip: str,
        grasping_width: float = 0.05,
        speed: float = 0.1,
        force: float = 5.0,
        epsilon_inner: float = 0.005,
        epsilon_outer: float = 0.005,
        async_control: bool = False,
    ) -> None: ...

class FHState(rcs._core.common.GripperState):
    def __init__(self) -> None: ...
    @property
    def bool_state(self) -> bool: ...
    @property
    def is_grasped(self) -> bool: ...
    @property
    def is_moving(self) -> bool: ...
    @property
    def last_commanded_width(self) -> float: ...
    @property
    def max_unnormalized_width(self) -> float: ...
    @property
    def temperature(self) -> int: ...
    @property
    def width(self) -> float: ...

class Franka(rcs._core.common.Robot):
    def __init__(self, cfg: FrankaConfig, ik: rcs._core.common.Kinematics | None = None) -> None: ...
    def automatic_error_recovery(self) -> None: ...
    def controller_set_joint_position(
        self, desired_q: numpy.ndarray[tuple[typing.Literal[7]], numpy.dtype[numpy.float64]]
    ) -> None: ...
    def double_tap_robot_to_continue(self) -> None: ...
    def get_config(self) -> FrankaConfig: ...
    def get_state(self) -> FrankaState: ...
    def osc_set_cartesian_position(self, desired_pos_EE_in_base_frame: rcs._core.common.Pose) -> None: ...
    def set_cartesian_position_ik(
        self, pose: rcs._core.common.Pose, max_time: float, elbow: float | None, max_force: float | None = 5
    ) -> None: ...
    def set_cartesian_position_internal(self, pose: rcs._core.common.Pose) -> None: ...
    def set_config(self, cfg: FrankaConfig) -> bool: ...
    def set_default_robot_behavior(self) -> None: ...
    def set_guiding_mode(
        self,
        x: bool = True,
        y: bool = True,
        z: bool = True,
        roll: bool = True,
        pitch: bool = True,
        yaw: bool = True,
        elbow: bool = True,
    ) -> None: ...
    def stop_control_thread(self) -> None: ...
    def zero_torque_guiding(self) -> None: ...

class FrankaConfig(rcs._core.common.RobotConfig):
    async_control: bool
    ignore_realtime: bool
    ik_solver: IKSolver
    ip: str
    load_parameters: FrankaLoad | None
    nominal_end_effector_frame: rcs._core.common.Pose | None
    speed_factor: float
    tcp_offset_configured_in_desk: bool
    world_to_robot: rcs._core.common.Pose | None

class FrankaHand(rcs._core.common.Gripper):
    def __init__(self, cfg: FHConfig) -> None: ...
    def close(self) -> None: ...
    def get_config(self) -> FHConfig: ...
    def get_state(self) -> FHState: ...
    def homing(self) -> bool: ...
    def is_grasped(self) -> bool: ...
    def set_config(self, cfg: FHConfig) -> bool: ...

class FrankaLoad:
    f_x_cload: numpy.ndarray[tuple[typing.Literal[3]], numpy.dtype[numpy.float64]] | None
    load_inertia: numpy.ndarray[tuple[typing.Literal[3], typing.Literal[3]], numpy.dtype[numpy.float64]] | None
    load_mass: float
    def __init__(self) -> None: ...

class IKSolver:
    """
    Members:

      franka_ik

      rcs_ik
    """

    __members__: typing.ClassVar[
        dict[str, IKSolver]
    ]  # value = {'franka_ik': <IKSolver.franka_ik: 0>, 'rcs_ik': <IKSolver.rcs_ik: 1>}
    franka_ik: typing.ClassVar[IKSolver]  # value = <IKSolver.franka_ik: 0>
    rcs_ik: typing.ClassVar[IKSolver]  # value = <IKSolver.rcs_ik: 1>
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class RobotMode:
    """
    Members:

      kOther

      kIdle

      kMove

      kGuiding

      kReflex

      kUserStopped

      kAutomaticErrorRecovery
    """

    __members__: typing.ClassVar[
        dict[str, RobotMode]
    ]  # value = {'kOther': <RobotMode.kOther: 0>, 'kIdle': <RobotMode.kIdle: 1>, 'kMove': <RobotMode.kMove: 2>, 'kGuiding': <RobotMode.kGuiding: 3>, 'kReflex': <RobotMode.kReflex: 4>, 'kUserStopped': <RobotMode.kUserStopped: 5>, 'kAutomaticErrorRecovery': <RobotMode.kAutomaticErrorRecovery: 6>}
    kAutomaticErrorRecovery: typing.ClassVar[RobotMode]  # value = <RobotMode.kAutomaticErrorRecovery: 6>
    kGuiding: typing.ClassVar[RobotMode]  # value = <RobotMode.kGuiding: 3>
    kIdle: typing.ClassVar[RobotMode]  # value = <RobotMode.kIdle: 1>
    kMove: typing.ClassVar[RobotMode]  # value = <RobotMode.kMove: 2>
    kOther: typing.ClassVar[RobotMode]  # value = <RobotMode.kOther: 0>
    kReflex: typing.ClassVar[RobotMode]  # value = <RobotMode.kReflex: 4>
    kUserStopped: typing.ClassVar[RobotMode]  # value = <RobotMode.kUserStopped: 5>
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class RobotState:
    def __init__(self) -> None: ...
    @property
    def EE_T_K(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(16)]: ...
    @property
    def F_T_EE(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(16)]: ...
    @property
    def F_T_NE(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(16)]: ...
    @property
    def F_x_Cee(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(3)]: ...
    @property
    def F_x_Cload(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(3)]: ...
    @property
    def F_x_Ctotal(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(3)]: ...
    @property
    def I_ee(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(9)]: ...
    @property
    def I_load(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(9)]: ...
    @property
    def I_total(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(9)]: ...
    @property
    def K_F_ext_hat_K(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(6)]: ...
    @property
    def NE_T_EE(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(16)]: ...
    @property
    def O_F_ext_hat_K(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(6)]: ...
    @property
    def O_T_EE(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(16)]: ...
    @property
    def O_T_EE_c(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(16)]: ...
    @property
    def O_T_EE_d(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(16)]: ...
    @property
    def O_dP_EE_c(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(6)]: ...
    @property
    def O_dP_EE_d(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(6)]: ...
    @property
    def O_ddP_EE_c(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(6)]: ...
    @property
    def O_ddP_O(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(3)]: ...
    @property
    def cartesian_collision(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(6)]: ...
    @property
    def cartesian_contact(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(6)]: ...
    @property
    def control_command_success_rate(self) -> float: ...
    @property
    def ddelbow_c(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]: ...
    @property
    def ddq_d(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def delbow_c(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]: ...
    @property
    def dq(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def dq_d(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def dtau_J(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def dtheta(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def elbow(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]: ...
    @property
    def elbow_c(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]: ...
    @property
    def elbow_d(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]: ...
    @property
    def joint_collision(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def joint_contact(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def m_ee(self) -> float: ...
    @property
    def m_load(self) -> float: ...
    @property
    def m_total(self) -> float: ...
    @property
    def q(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def q_d(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def robot_mode(self) -> RobotMode: ...
    @property
    def tau_J(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def tau_J_d(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def tau_ext_hat_filtered(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...
    @property
    def theta(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(7)]: ...

class FR3Config(FrankaConfig):
    def __init__(
        self,
        ip: str,
        ik_solver: IKSolver = ...,
        speed_factor: float = 0.2,
        load_parameters: FrankaLoad | None = None,
        nominal_end_effector_frame: rcs._core.common.Pose | None = None,
        world_to_robot: rcs._core.common.Pose | None = None,
        async_control: bool = False,
        tcp_offset_configured_in_desk: bool = True,
        ignore_realtime: bool = False,
        tcp_offset: rcs._core.common.Pose = ...,
        attachment_site: str = "attachment_site",
        kinematic_model_path: str = "assets/scenes/fr3_empty_world/robot.xml",
    ) -> None: ...

class PandaConfig(FrankaConfig):
    def __init__(
        self,
        ip: str,
        ik_solver: IKSolver = ...,
        speed_factor: float = 0.2,
        load_parameters: FrankaLoad | None = None,
        nominal_end_effector_frame: rcs._core.common.Pose | None = None,
        world_to_robot: rcs._core.common.Pose | None = None,
        async_control: bool = False,
        tcp_offset_configured_in_desk: bool = True,
        ignore_realtime: bool = False,
        tcp_offset: rcs._core.common.Pose = ...,
        attachment_site: str = "attachment_site",
        kinematic_model_path: str = "assets/scenes/fr3_empty_world/robot.xml",
    ) -> None: ...

class FrankaState(rcs._core.common.RobotState):
    def __init__(self) -> None: ...
    @property
    def robot_state(self) -> RobotState: ...

franka_ik: IKSolver  # value = <IKSolver.franka_ik: 0>
kAutomaticErrorRecovery: RobotMode  # value = <RobotMode.kAutomaticErrorRecovery: 6>
kGuiding: RobotMode  # value = <RobotMode.kGuiding: 3>
kIdle: RobotMode  # value = <RobotMode.kIdle: 1>
kMove: RobotMode  # value = <RobotMode.kMove: 2>
kOther: RobotMode  # value = <RobotMode.kOther: 0>
kReflex: RobotMode  # value = <RobotMode.kReflex: 4>
kUserStopped: RobotMode  # value = <RobotMode.kUserStopped: 5>
rcs_ik: IKSolver  # value = <IKSolver.rcs_ik: 1>
